/*
This file is automatically generated
DO NOT MODIFY BY HAND
Ft_Esd_Layout_Stretch
C Source
*/

#include "Ft_Esd_Layout_Stretch.h"

#include "Esd_Context.h"
ESD_CORE_EXPORT void Esd_Noop(void *context);


static Ft_Esd_WidgetSlots s_Ft_Esd_Layout_Stretch__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_Widget_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Ft_Esd_Widget_Update,
	(void(*)(void *))Ft_Esd_Widget_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Ft_Esd_Widget_End,
};


void Ft_Esd_Layout_Stretch__Initializer(Ft_Esd_Layout_Stretch *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Ft_Esd_Layout_Stretch_CLASSID;
	context->Widget.Slots = &s_Ft_Esd_Layout_Stretch__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 50;
	context->Widget.LocalHeight = 50;
	context->Weight = 1;
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	Ft_Esd_Layout_Stretch Instance;
} Ft_Esd_Layout_Stretch__ESD;


void *Ft_Esd_Layout_Stretch__Create__ESD()
{
	Ft_Esd_Layout_Stretch__ESD *context = (Ft_Esd_Layout_Stretch__ESD *)malloc(sizeof(Ft_Esd_Layout_Stretch__ESD));
	if (context)
	{
		Ft_Esd_Layout_Stretch__Initializer(&context->Instance);
		context->Instance.Owner = context;
	}
	else
	{
		eve_printf_debug("Out of memory (Ft_Esd_Layout_Stretch__Create__ESD)");
	}
	return context;
}

void Ft_Esd_Layout_Stretch__Destroy__ESD(void *context)
{
	free(context);
}

void Ft_Esd_Layout_Stretch__Set_Weight__ESD(void *context, ft_int16_t value) { ((Ft_Esd_Layout_Stretch__ESD *)context)->Instance.Weight = value; }

#endif /* ESD_SIMULATION */

/* end of file */
