/*
This file is automatically generated
DO NOT MODIFY BY HAND
Usr_Page
C Source
*/

#include "Usr_Page.h"

#include "Esd_Context.h"
ESD_CORE_EXPORT void Esd_Noop(void *context);


static Ft_Esd_WidgetSlots s_Usr_Page__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_Widget_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Ft_Esd_Widget_Update,
	(void(*)(void *))Ft_Esd_Widget_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Usr_Page_End,
};


void Usr_Page__Fixed_Position__Initializer(Usr_Page *context)
{
	Ft_Esd_Layout_Fixed *object = (Ft_Esd_Layout_Fixed *)&context->Fixed_Position;
	Ft_Esd_Layout_Fixed__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void Usr_Page__Initializer(Usr_Page *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Usr_Page_CLASSID;
	context->Widget.Slots = &s_Usr_Page__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 400;
	context->Widget.LocalHeight = 300;
	Usr_Page__Fixed_Position__Initializer(context);
}

void Usr_Page_End(Usr_Page *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fixed_Position); 
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	Usr_Page Instance;
} Usr_Page__ESD;


void *Usr_Page__Create__ESD()
{
	Usr_Page__ESD *context = (Usr_Page__ESD *)malloc(sizeof(Usr_Page__ESD));
	if (context)
	{
		Usr_Page__Initializer(&context->Instance);
		context->Instance.Owner = context;
	}
	else
	{
		eve_printf_debug("Out of memory (Usr_Page__Create__ESD)");
	}
	return context;
}

void Usr_Page__Destroy__ESD(void *context)
{
	free(context);
}


#endif /* ESD_SIMULATION */

/* end of file */
