/*
This file is automatically generated
DO NOT MODIFY BY HAND
Usr_Page
Header
*/

#ifndef Usr_Page__H
#define Usr_Page__H

#include "Esd_Base.h"
#include "Ft_Esd.h"
#include "Ft_Esd_Layout_Fixed.h"
#include "Ft_Esd_Widget.h"

#ifndef ESD_LOGIC
#define ESD_LOGIC(name, ...)
#define ESD_ACTOR(name, ...)
#define ESD_WIDGET(name, ...)
#define ESD_PAGE(name, ...)
#define ESD_APPLICATION(name, ...)
#define ESD_INPUT(name, ...)
#define ESD_OUTPUT(name, ...)
#define ESD_SLOT(name, ...)
#define ESD_SIGNAL(name, ...)
#define ESD_VARIABLE(name, ...)
#define ESD_WRITER(name, ...)
#endif

#define Usr_Page_CLASSID 0x09198A9A
ESD_SYMBOL(Usr_Page_CLASSID, Type = esd_classid_t)

ESD_WIDGET(Usr_Page, Include = "Usr_Page.h", Callback, X = 0, Y = 0, Width = 400, Height = 300, Page)
typedef struct
{
	union
	{
		void *Owner;
		Ft_Esd_Widget Widget;
	};
	Ft_Esd_Layout_Fixed Fixed_Position;
} Usr_Page;

void Usr_Page__Initializer(Usr_Page *context);

ESD_SLOT(End)
void Usr_Page_End(Usr_Page *context);

#endif /* Usr_Page__H */

/* end of file */
