/*
This file is automatically generated
EVE_CoCmd__h
Simulation wrapper
*/

/* Simulation wrapper for 'EVE_CoCmd_clock' */

#ifdef ESD_SIMULATION
#include <stdlib.h>
#include "Esd_Core.h"

typedef struct
{
	EVE_HalContext * phost;
	int16_t x;
	int16_t y;
	int16_t r;
	uint16_t options;
	uint16_t height;
	uint16_t m;
	uint16_t s;
	uint16_t ms;
} EVE_CoCmd_clock__ESD;

void EVE_CoCmd_clock__Set_phost__ESD(void *context, EVE_HalContext * value) { ((EVE_CoCmd_clock__ESD *)context)->phost = value; }
void EVE_CoCmd_clock__Set_x__ESD(void *context, int16_t value) { ((EVE_CoCmd_clock__ESD *)context)->x = value; }
void EVE_CoCmd_clock__Set_y__ESD(void *context, int16_t value) { ((EVE_CoCmd_clock__ESD *)context)->y = value; }
void EVE_CoCmd_clock__Set_r__ESD(void *context, int16_t value) { ((EVE_CoCmd_clock__ESD *)context)->r = value; }
void EVE_CoCmd_clock__Set_options__ESD(void *context, uint16_t value) { ((EVE_CoCmd_clock__ESD *)context)->options = value; }
void EVE_CoCmd_clock__Set_height__ESD(void *context, uint16_t value) { ((EVE_CoCmd_clock__ESD *)context)->height = value; }
void EVE_CoCmd_clock__Set_m__ESD(void *context, uint16_t value) { ((EVE_CoCmd_clock__ESD *)context)->m = value; }
void EVE_CoCmd_clock__Set_s__ESD(void *context, uint16_t value) { ((EVE_CoCmd_clock__ESD *)context)->s = value; }
void EVE_CoCmd_clock__Set_ms__ESD(void *context, uint16_t value) { ((EVE_CoCmd_clock__ESD *)context)->ms = value; }

void *EVE_CoCmd_clock__Create__ESD()
{
	EVE_CoCmd_clock__ESD *context = (EVE_CoCmd_clock__ESD *)malloc(sizeof(EVE_CoCmd_clock__ESD));
	if (context)
	{
		context->phost = Esd_GetHost();
		context->x = 0;
		context->y = 0;
		context->r = 40;
		context->options = 0;
		context->height = 0U;
		context->m = 0U;
		context->s = 0U;
		context->ms = 0U;
	}
	else
	{
		eve_printf_debug("Out of memory (EVE_CoCmd_clock__Create__ESD)");
	}
	return context;
}

void EVE_CoCmd_clock__Destroy__ESD(void *context)
{
	free(context);
}

void EVE_CoCmd_clock_Render(EVE_CoCmd_clock__ESD *context)
{
	EVE_CoCmd_clock(context->phost, context->x, context->y, context->r, context->options, context->height, context->m, context->s, context->ms);
}

#endif /* ESD_SIMULATION */

/* Simulation wrapper for 'EVE_CoCmd_dial' */

#ifdef ESD_SIMULATION
#include <stdlib.h>
#include "Esd_Core.h"

typedef struct
{
	EVE_HalContext * phost;
	int16_t x;
	int16_t y;
	int16_t r;
	uint16_t options;
	uint16_t val;
} EVE_CoCmd_dial__ESD;

void EVE_CoCmd_dial__Set_phost__ESD(void *context, EVE_HalContext * value) { ((EVE_CoCmd_dial__ESD *)context)->phost = value; }
void EVE_CoCmd_dial__Set_x__ESD(void *context, int16_t value) { ((EVE_CoCmd_dial__ESD *)context)->x = value; }
void EVE_CoCmd_dial__Set_y__ESD(void *context, int16_t value) { ((EVE_CoCmd_dial__ESD *)context)->y = value; }
void EVE_CoCmd_dial__Set_r__ESD(void *context, int16_t value) { ((EVE_CoCmd_dial__ESD *)context)->r = value; }
void EVE_CoCmd_dial__Set_options__ESD(void *context, uint16_t value) { ((EVE_CoCmd_dial__ESD *)context)->options = value; }
void EVE_CoCmd_dial__Set_val__ESD(void *context, uint16_t value) { ((EVE_CoCmd_dial__ESD *)context)->val = value; }

void *EVE_CoCmd_dial__Create__ESD()
{
	EVE_CoCmd_dial__ESD *context = (EVE_CoCmd_dial__ESD *)malloc(sizeof(EVE_CoCmd_dial__ESD));
	if (context)
	{
		context->phost = Esd_GetHost();
		context->x = 0;
		context->y = 0;
		context->r = 40;
		context->options = 0;
		context->val = 0U;
	}
	else
	{
		eve_printf_debug("Out of memory (EVE_CoCmd_dial__Create__ESD)");
	}
	return context;
}

void EVE_CoCmd_dial__Destroy__ESD(void *context)
{
	free(context);
}

void EVE_CoCmd_dial_Render(EVE_CoCmd_dial__ESD *context)
{
	EVE_CoCmd_dial(context->phost, context->x, context->y, context->r, context->options, context->val);
}

#endif /* ESD_SIMULATION */

/* Simulation wrapper for 'EVE_CoCmd_gauge' */

#ifdef ESD_SIMULATION
#include <stdlib.h>
#include "Esd_Core.h"

typedef struct
{
	EVE_HalContext * phost;
	int16_t x;
	int16_t y;
	int16_t r;
	uint16_t options;
	uint16_t major;
	uint16_t minor;
	uint16_t val;
	uint16_t range;
} EVE_CoCmd_gauge__ESD;

void EVE_CoCmd_gauge__Set_phost__ESD(void *context, EVE_HalContext * value) { ((EVE_CoCmd_gauge__ESD *)context)->phost = value; }
void EVE_CoCmd_gauge__Set_x__ESD(void *context, int16_t value) { ((EVE_CoCmd_gauge__ESD *)context)->x = value; }
void EVE_CoCmd_gauge__Set_y__ESD(void *context, int16_t value) { ((EVE_CoCmd_gauge__ESD *)context)->y = value; }
void EVE_CoCmd_gauge__Set_r__ESD(void *context, int16_t value) { ((EVE_CoCmd_gauge__ESD *)context)->r = value; }
void EVE_CoCmd_gauge__Set_options__ESD(void *context, uint16_t value) { ((EVE_CoCmd_gauge__ESD *)context)->options = value; }
void EVE_CoCmd_gauge__Set_major__ESD(void *context, uint16_t value) { ((EVE_CoCmd_gauge__ESD *)context)->major = value; }
void EVE_CoCmd_gauge__Set_minor__ESD(void *context, uint16_t value) { ((EVE_CoCmd_gauge__ESD *)context)->minor = value; }
void EVE_CoCmd_gauge__Set_val__ESD(void *context, uint16_t value) { ((EVE_CoCmd_gauge__ESD *)context)->val = value; }
void EVE_CoCmd_gauge__Set_range__ESD(void *context, uint16_t value) { ((EVE_CoCmd_gauge__ESD *)context)->range = value; }

void *EVE_CoCmd_gauge__Create__ESD()
{
	EVE_CoCmd_gauge__ESD *context = (EVE_CoCmd_gauge__ESD *)malloc(sizeof(EVE_CoCmd_gauge__ESD));
	if (context)
	{
		context->phost = Esd_GetHost();
		context->x = 0;
		context->y = 0;
		context->r = 40;
		context->options = 0;
		context->major = 0U;
		context->minor = 0U;
		context->val = 0U;
		context->range = 0U;
	}
	else
	{
		eve_printf_debug("Out of memory (EVE_CoCmd_gauge__Create__ESD)");
	}
	return context;
}

void EVE_CoCmd_gauge__Destroy__ESD(void *context)
{
	free(context);
}

void EVE_CoCmd_gauge_Render(EVE_CoCmd_gauge__ESD *context)
{
	EVE_CoCmd_gauge(context->phost, context->x, context->y, context->r, context->options, context->major, context->minor, context->val, context->range);
}

#endif /* ESD_SIMULATION */

/* Simulation wrapper for 'EVE_CoCmd_keys' */

#ifdef ESD_SIMULATION
#include <stdlib.h>
#include "Esd_Core.h"

void EVE_CoCmd_keys(EVE_HalContext *, int16_t, int16_t, int16_t, int16_t, int16_t, uint16_t, const char *);

typedef struct
{
	EVE_HalContext * phost;
	int16_t x;
	int16_t y;
	int16_t width;
	int16_t height;
	int16_t font;
	uint16_t options;
	const char * s;
} EVE_CoCmd_keys__ESD;

void EVE_CoCmd_keys__Set_phost__ESD(void *context, EVE_HalContext * value) { ((EVE_CoCmd_keys__ESD *)context)->phost = value; }
void EVE_CoCmd_keys__Set_x__ESD(void *context, int16_t value) { ((EVE_CoCmd_keys__ESD *)context)->x = value; }
void EVE_CoCmd_keys__Set_y__ESD(void *context, int16_t value) { ((EVE_CoCmd_keys__ESD *)context)->y = value; }
void EVE_CoCmd_keys__Set_width__ESD(void *context, int16_t value) { ((EVE_CoCmd_keys__ESD *)context)->width = value; }
void EVE_CoCmd_keys__Set_height__ESD(void *context, int16_t value) { ((EVE_CoCmd_keys__ESD *)context)->height = value; }
void EVE_CoCmd_keys__Set_font__ESD(void *context, int16_t value) { ((EVE_CoCmd_keys__ESD *)context)->font = value; }
void EVE_CoCmd_keys__Set_options__ESD(void *context, uint16_t value) { ((EVE_CoCmd_keys__ESD *)context)->options = value; }
void EVE_CoCmd_keys__Set_s__ESD(void *context, const char * value) { ((EVE_CoCmd_keys__ESD *)context)->s = value; }

void *EVE_CoCmd_keys__Create__ESD()
{
	EVE_CoCmd_keys__ESD *context = (EVE_CoCmd_keys__ESD *)malloc(sizeof(EVE_CoCmd_keys__ESD));
	if (context)
	{
		context->phost = Esd_GetHost();
		context->x = 0;
		context->y = 0;
		context->width = 60;
		context->height = 40;
		context->font = 21;
		context->options = 0;
		context->s = "Button";
	}
	else
	{
		eve_printf_debug("Out of memory (EVE_CoCmd_keys__Create__ESD)");
	}
	return context;
}

void EVE_CoCmd_keys__Destroy__ESD(void *context)
{
	free(context);
}

void EVE_CoCmd_keys_Render(EVE_CoCmd_keys__ESD *context)
{
	EVE_CoCmd_keys(context->phost, context->x, context->y, context->width, context->height, context->font, context->options, context->s);
}

#endif /* ESD_SIMULATION */

/* Simulation wrapper for 'EVE_CoCmd_number' */

#ifdef ESD_SIMULATION
#include <stdlib.h>
#include "Esd_Core.h"

void EVE_CoCmd_number(EVE_HalContext *, int16_t, int16_t, int16_t, uint16_t, int32_t);

typedef struct
{
	EVE_HalContext * phost;
	int16_t x;
	int16_t y;
	int16_t font;
	uint16_t options;
	int32_t n;
} EVE_CoCmd_number__ESD;

void EVE_CoCmd_number__Set_phost__ESD(void *context, EVE_HalContext * value) { ((EVE_CoCmd_number__ESD *)context)->phost = value; }
void EVE_CoCmd_number__Set_x__ESD(void *context, int16_t value) { ((EVE_CoCmd_number__ESD *)context)->x = value; }
void EVE_CoCmd_number__Set_y__ESD(void *context, int16_t value) { ((EVE_CoCmd_number__ESD *)context)->y = value; }
void EVE_CoCmd_number__Set_font__ESD(void *context, int16_t value) { ((EVE_CoCmd_number__ESD *)context)->font = value; }
void EVE_CoCmd_number__Set_options__ESD(void *context, uint16_t value) { ((EVE_CoCmd_number__ESD *)context)->options = value; }
void EVE_CoCmd_number__Set_n__ESD(void *context, int32_t value) { ((EVE_CoCmd_number__ESD *)context)->n = value; }

void *EVE_CoCmd_number__Create__ESD()
{
	EVE_CoCmd_number__ESD *context = (EVE_CoCmd_number__ESD *)malloc(sizeof(EVE_CoCmd_number__ESD));
	if (context)
	{
		context->phost = Esd_GetHost();
		context->x = 0;
		context->y = 0;
		context->font = 21;
		context->options = 256U;
		context->n = 0L;
	}
	else
	{
		eve_printf_debug("Out of memory (EVE_CoCmd_number__Create__ESD)");
	}
	return context;
}

void EVE_CoCmd_number__Destroy__ESD(void *context)
{
	free(context);
}

void EVE_CoCmd_number_Render(EVE_CoCmd_number__ESD *context)
{
	EVE_CoCmd_number(context->phost, context->x, context->y, context->font, context->options, context->n);
}

#endif /* ESD_SIMULATION */

/* Simulation wrapper for 'EVE_CoCmd_progress' */

#ifdef ESD_SIMULATION
#include <stdlib.h>
#include "Esd_Core.h"

typedef struct
{
	EVE_HalContext * phost;
	int16_t x;
	int16_t y;
	int16_t width;
	int16_t height;
	uint16_t options;
	uint16_t val;
	uint16_t range;
} EVE_CoCmd_progress__ESD;

void EVE_CoCmd_progress__Set_phost__ESD(void *context, EVE_HalContext * value) { ((EVE_CoCmd_progress__ESD *)context)->phost = value; }
void EVE_CoCmd_progress__Set_x__ESD(void *context, int16_t value) { ((EVE_CoCmd_progress__ESD *)context)->x = value; }
void EVE_CoCmd_progress__Set_y__ESD(void *context, int16_t value) { ((EVE_CoCmd_progress__ESD *)context)->y = value; }
void EVE_CoCmd_progress__Set_width__ESD(void *context, int16_t value) { ((EVE_CoCmd_progress__ESD *)context)->width = value; }
void EVE_CoCmd_progress__Set_height__ESD(void *context, int16_t value) { ((EVE_CoCmd_progress__ESD *)context)->height = value; }
void EVE_CoCmd_progress__Set_options__ESD(void *context, uint16_t value) { ((EVE_CoCmd_progress__ESD *)context)->options = value; }
void EVE_CoCmd_progress__Set_val__ESD(void *context, uint16_t value) { ((EVE_CoCmd_progress__ESD *)context)->val = value; }
void EVE_CoCmd_progress__Set_range__ESD(void *context, uint16_t value) { ((EVE_CoCmd_progress__ESD *)context)->range = value; }

void *EVE_CoCmd_progress__Create__ESD()
{
	EVE_CoCmd_progress__ESD *context = (EVE_CoCmd_progress__ESD *)malloc(sizeof(EVE_CoCmd_progress__ESD));
	if (context)
	{
		context->phost = Esd_GetHost();
		context->x = 0;
		context->y = 0;
		context->width = 60;
		context->height = 40;
		context->options = 0;
		context->val = 0U;
		context->range = 0U;
	}
	else
	{
		eve_printf_debug("Out of memory (EVE_CoCmd_progress__Create__ESD)");
	}
	return context;
}

void EVE_CoCmd_progress__Destroy__ESD(void *context)
{
	free(context);
}

void EVE_CoCmd_progress_Render(EVE_CoCmd_progress__ESD *context)
{
	EVE_CoCmd_progress(context->phost, context->x, context->y, context->width, context->height, context->options, context->val, context->range);
}

#endif /* ESD_SIMULATION */

/* Simulation wrapper for 'EVE_CoCmd_scrollbar' */

#ifdef ESD_SIMULATION
#include <stdlib.h>
#include "Esd_Core.h"

typedef struct
{
	EVE_HalContext * phost;
	int16_t x;
	int16_t y;
	int16_t width;
	int16_t height;
	uint16_t options;
	uint16_t val;
	uint16_t size;
	uint16_t range;
} EVE_CoCmd_scrollbar__ESD;

void EVE_CoCmd_scrollbar__Set_phost__ESD(void *context, EVE_HalContext * value) { ((EVE_CoCmd_scrollbar__ESD *)context)->phost = value; }
void EVE_CoCmd_scrollbar__Set_x__ESD(void *context, int16_t value) { ((EVE_CoCmd_scrollbar__ESD *)context)->x = value; }
void EVE_CoCmd_scrollbar__Set_y__ESD(void *context, int16_t value) { ((EVE_CoCmd_scrollbar__ESD *)context)->y = value; }
void EVE_CoCmd_scrollbar__Set_width__ESD(void *context, int16_t value) { ((EVE_CoCmd_scrollbar__ESD *)context)->width = value; }
void EVE_CoCmd_scrollbar__Set_height__ESD(void *context, int16_t value) { ((EVE_CoCmd_scrollbar__ESD *)context)->height = value; }
void EVE_CoCmd_scrollbar__Set_options__ESD(void *context, uint16_t value) { ((EVE_CoCmd_scrollbar__ESD *)context)->options = value; }
void EVE_CoCmd_scrollbar__Set_val__ESD(void *context, uint16_t value) { ((EVE_CoCmd_scrollbar__ESD *)context)->val = value; }
void EVE_CoCmd_scrollbar__Set_size__ESD(void *context, uint16_t value) { ((EVE_CoCmd_scrollbar__ESD *)context)->size = value; }
void EVE_CoCmd_scrollbar__Set_range__ESD(void *context, uint16_t value) { ((EVE_CoCmd_scrollbar__ESD *)context)->range = value; }

void *EVE_CoCmd_scrollbar__Create__ESD()
{
	EVE_CoCmd_scrollbar__ESD *context = (EVE_CoCmd_scrollbar__ESD *)malloc(sizeof(EVE_CoCmd_scrollbar__ESD));
	if (context)
	{
		context->phost = Esd_GetHost();
		context->x = 0;
		context->y = 0;
		context->width = 60;
		context->height = 40;
		context->options = 0;
		context->val = 0U;
		context->size = 0U;
		context->range = 0U;
	}
	else
	{
		eve_printf_debug("Out of memory (EVE_CoCmd_scrollbar__Create__ESD)");
	}
	return context;
}

void EVE_CoCmd_scrollbar__Destroy__ESD(void *context)
{
	free(context);
}

void EVE_CoCmd_scrollbar_Render(EVE_CoCmd_scrollbar__ESD *context)
{
	EVE_CoCmd_scrollbar(context->phost, context->x, context->y, context->width, context->height, context->options, context->val, context->size, context->range);
}

#endif /* ESD_SIMULATION */

/* Simulation wrapper for 'EVE_CoCmd_slider' */

#ifdef ESD_SIMULATION
#include <stdlib.h>
#include "Esd_Core.h"

typedef struct
{
	EVE_HalContext * phost;
	int16_t x;
	int16_t y;
	int16_t width;
	int16_t height;
	uint16_t options;
	uint16_t val;
	uint16_t range;
} EVE_CoCmd_slider__ESD;

void EVE_CoCmd_slider__Set_phost__ESD(void *context, EVE_HalContext * value) { ((EVE_CoCmd_slider__ESD *)context)->phost = value; }
void EVE_CoCmd_slider__Set_x__ESD(void *context, int16_t value) { ((EVE_CoCmd_slider__ESD *)context)->x = value; }
void EVE_CoCmd_slider__Set_y__ESD(void *context, int16_t value) { ((EVE_CoCmd_slider__ESD *)context)->y = value; }
void EVE_CoCmd_slider__Set_width__ESD(void *context, int16_t value) { ((EVE_CoCmd_slider__ESD *)context)->width = value; }
void EVE_CoCmd_slider__Set_height__ESD(void *context, int16_t value) { ((EVE_CoCmd_slider__ESD *)context)->height = value; }
void EVE_CoCmd_slider__Set_options__ESD(void *context, uint16_t value) { ((EVE_CoCmd_slider__ESD *)context)->options = value; }
void EVE_CoCmd_slider__Set_val__ESD(void *context, uint16_t value) { ((EVE_CoCmd_slider__ESD *)context)->val = value; }
void EVE_CoCmd_slider__Set_range__ESD(void *context, uint16_t value) { ((EVE_CoCmd_slider__ESD *)context)->range = value; }

void *EVE_CoCmd_slider__Create__ESD()
{
	EVE_CoCmd_slider__ESD *context = (EVE_CoCmd_slider__ESD *)malloc(sizeof(EVE_CoCmd_slider__ESD));
	if (context)
	{
		context->phost = Esd_GetHost();
		context->x = 0;
		context->y = 0;
		context->width = 60;
		context->height = 40;
		context->options = 0;
		context->val = 0U;
		context->range = 0U;
	}
	else
	{
		eve_printf_debug("Out of memory (EVE_CoCmd_slider__Create__ESD)");
	}
	return context;
}

void EVE_CoCmd_slider__Destroy__ESD(void *context)
{
	free(context);
}

void EVE_CoCmd_slider_Render(EVE_CoCmd_slider__ESD *context)
{
	EVE_CoCmd_slider(context->phost, context->x, context->y, context->width, context->height, context->options, context->val, context->range);
}

#endif /* ESD_SIMULATION */

/* Simulation wrapper for 'EVE_CoCmd_text_ex' */

#ifdef ESD_SIMULATION
#include <stdlib.h>
#include "Esd_Core.h"

void EVE_CoCmd_text_ex(EVE_HalContext *, int16_t, int16_t, int16_t, uint16_t, bool, int16_t, int16_t, const char *);

typedef struct
{
	EVE_HalContext * phost;
	int16_t x;
	int16_t y;
	int16_t font;
	uint16_t options;
	bool bottom;
	int16_t baseLine;
	int16_t capsHeight;
	const char * s;
} EVE_CoCmd_text_ex__ESD;

void EVE_CoCmd_text_ex__Set_phost__ESD(void *context, EVE_HalContext * value) { ((EVE_CoCmd_text_ex__ESD *)context)->phost = value; }
void EVE_CoCmd_text_ex__Set_x__ESD(void *context, int16_t value) { ((EVE_CoCmd_text_ex__ESD *)context)->x = value; }
void EVE_CoCmd_text_ex__Set_y__ESD(void *context, int16_t value) { ((EVE_CoCmd_text_ex__ESD *)context)->y = value; }
void EVE_CoCmd_text_ex__Set_font__ESD(void *context, int16_t value) { ((EVE_CoCmd_text_ex__ESD *)context)->font = value; }
void EVE_CoCmd_text_ex__Set_options__ESD(void *context, uint16_t value) { ((EVE_CoCmd_text_ex__ESD *)context)->options = value; }
void EVE_CoCmd_text_ex__Set_bottom__ESD(void *context, bool value) { ((EVE_CoCmd_text_ex__ESD *)context)->bottom = value; }
void EVE_CoCmd_text_ex__Set_baseLine__ESD(void *context, int16_t value) { ((EVE_CoCmd_text_ex__ESD *)context)->baseLine = value; }
void EVE_CoCmd_text_ex__Set_capsHeight__ESD(void *context, int16_t value) { ((EVE_CoCmd_text_ex__ESD *)context)->capsHeight = value; }
void EVE_CoCmd_text_ex__Set_s__ESD(void *context, const char * value) { ((EVE_CoCmd_text_ex__ESD *)context)->s = value; }

void *EVE_CoCmd_text_ex__Create__ESD()
{
	EVE_CoCmd_text_ex__ESD *context = (EVE_CoCmd_text_ex__ESD *)malloc(sizeof(EVE_CoCmd_text_ex__ESD));
	if (context)
	{
		context->phost = Esd_GetHost();
		context->x = 0;
		context->y = 0;
		context->font = 21;
		context->options = 0;
		context->bottom = 0;
		context->baseLine = 0;
		context->capsHeight = 0;
		context->s = "Text";
	}
	else
	{
		eve_printf_debug("Out of memory (EVE_CoCmd_text_ex__Create__ESD)");
	}
	return context;
}

void EVE_CoCmd_text_ex__Destroy__ESD(void *context)
{
	free(context);
}

void EVE_CoCmd_text_ex_Render(EVE_CoCmd_text_ex__ESD *context)
{
	EVE_CoCmd_text_ex(context->phost, context->x, context->y, context->font, context->options, context->bottom, context->baseLine, context->capsHeight, context->s);
}

#endif /* ESD_SIMULATION */

/* end of file */
