/*
This file is automatically generated
DO NOT MODIFY BY HAND
Ft_Esd_LinearRoller
C Source
*/

/*
Comment :
Introduction:
This widget lets user choose a value by rolling a group of sticks linearly.
The main usage is for seeking radio channel.
Touch input is supported.
*/

#include "Ft_Esd_LinearRoller.h"

#include "Esd_Context.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);
int Ft_Esd_LinearRoller_Length__Default(void *context) { return 20L; }
ft_bool_t Ft_Esd_LinearRoller_Horizontal__Default(void *context) { return 1; }
int Ft_Esd_LinearRoller_MinValue__Default(void *context) { return 0L; }
int Ft_Esd_LinearRoller_Value__Default(void *context) { return 0L; }
int Ft_Esd_LinearRoller_MaxValue__Default(void *context) { return 100L; }
ft_bool_t Ft_Esd_LinearRoller_IsTrimToRange__Default(void *context) { return 1; }
ft_bool_t Ft_Esd_LinearRoller_ShowTrimRange__Default(void *context) { return 1; }
ft_bool_t Ft_Esd_LinearRoller_IsDisplayTick__Default(void *context) { return 1; }
ft_bool_t Ft_Esd_LinearRoller_IsDisplayMinor__Default(void *context) { return 1; }
ft_bool_t Ft_Esd_LinearRoller_IsDisplayAxis__Default(void *context) { return 1; }
int Ft_Esd_LinearRoller_MajorWidth__Default(void *context) { return 3L; }
int Ft_Esd_LinearRoller_MinorWidth__Default(void *context) { return 2L; }
int Ft_Esd_LinearRoller_TickWidth__Default(void *context) { return 1L; }
float Ft_Esd_LinearRoller_MajorLength__Default(void *context) { return 0.72f; }
float Ft_Esd_LinearRoller_MinorLength__Default(void *context) { return 0.6f; }
float Ft_Esd_LinearRoller_TickLength__Default(void *context) { return 0.56f; }
int Ft_Esd_LinearRoller_LabelPadding__Default(void *context) { return 30L; }

static int Ft_Esd_LinearRoller_TouchScroll_X__Property(void *context);
static int Ft_Esd_LinearRoller_TouchScroll_Y__Property(void *context);
static int Ft_Esd_LinearRoller_TouchScroll_Width__Property(void *context);
static int Ft_Esd_LinearRoller_TouchScroll_Height__Property(void *context);
static ft_bool_t Ft_Esd_LinearRoller_TouchScroll_EnableXScroll__Property(void *context);
static ft_bool_t Ft_Esd_LinearRoller_TouchScroll_EnableYScroll__Property(void *context);
static int Ft_Esd_LinearRoller_TouchScroll_MinX__Property(void *context);
static int Ft_Esd_LinearRoller_TouchScroll_DefaultX__Property(void *context);
static int Ft_Esd_LinearRoller_TouchScroll_MaxX__Property(void *context) { return 0L; }
static int Ft_Esd_LinearRoller_TouchScroll_MinY__Property(void *context);
static int Ft_Esd_LinearRoller_TouchScroll_DefaultY__Property(void *context);
static int Ft_Esd_LinearRoller_TouchScroll_MaxY__Property(void *context) { return 0L; }

static Ft_Esd_WidgetSlots s_Ft_Esd_LinearRoller__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_LinearRoller_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Ft_Esd_LinearRoller_Update,
	(void(*)(void *))Ft_Esd_LinearRoller_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Ft_Esd_Widget_End,
};


void Ft_Esd_LinearRoller__TouchScroll__Initializer(Ft_Esd_LinearRoller *context)
{
	Ft_Esd_TouchScrollLogic *object = (Ft_Esd_TouchScrollLogic *)&context->TouchScroll;
	Ft_Esd_TouchScrollLogic__Initializer(object);
	object->Owner = (void *)context;
	object->X = Ft_Esd_LinearRoller_TouchScroll_X__Property;
	object->Y = Ft_Esd_LinearRoller_TouchScroll_Y__Property;
	object->Width = Ft_Esd_LinearRoller_TouchScroll_Width__Property;
	object->Height = Ft_Esd_LinearRoller_TouchScroll_Height__Property;
	object->EnableXScroll = Ft_Esd_LinearRoller_TouchScroll_EnableXScroll__Property;
	object->EnableYScroll = Ft_Esd_LinearRoller_TouchScroll_EnableYScroll__Property;
	object->MinX = Ft_Esd_LinearRoller_TouchScroll_MinX__Property;
	object->DefaultX = Ft_Esd_LinearRoller_TouchScroll_DefaultX__Property;
	object->MaxX = Ft_Esd_LinearRoller_TouchScroll_MaxX__Property;
	object->MinY = Ft_Esd_LinearRoller_TouchScroll_MinY__Property;
	object->DefaultY = Ft_Esd_LinearRoller_TouchScroll_DefaultY__Property;
	object->MaxY = Ft_Esd_LinearRoller_TouchScroll_MaxY__Property;
}

void Ft_Esd_LinearRoller__Initializer(Ft_Esd_LinearRoller *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Ft_Esd_LinearRoller_CLASSID;
	context->Widget.Slots = &s_Ft_Esd_LinearRoller__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 317;
	context->Widget.LocalHeight = 484;
	context->Length = Ft_Esd_LinearRoller_Length__Default;
	context->Major = 10L;
	context->Minor = 5L;
	context->ColorMin = 0xff10e3dcUL;
	context->Ft_Esd_LinearRoller_UpdateCenterValue = 0L;
	context->ColorMax = 0xfffd0606UL;
	context->Horizontal = Ft_Esd_LinearRoller_Horizontal__Default;
	context->centerValue = 0L;
	context->centerColor = 0xfffcfcfcUL;
	context->MinValue = Ft_Esd_LinearRoller_MinValue__Default;
	context->Ft_Esd_LinearRoller_InitializeCenterValueWithMinMax = 0L;
	context->Value = Ft_Esd_LinearRoller_Value__Default;
	context->MaxValue = Ft_Esd_LinearRoller_MaxValue__Default;
	context->MinVariable = 0L;
	context->MaxVariable = 0L;
	context->Font = 26;
	context->valueVariable = 0L;
	context->ColorAxis = 0xffafd6caUL;
	context->IsTrimToRange = Ft_Esd_LinearRoller_IsTrimToRange__Default;
	context->ShowTrimRange = Ft_Esd_LinearRoller_ShowTrimRange__Default;
	context->IsDisplayTick = Ft_Esd_LinearRoller_IsDisplayTick__Default;
	context->IsDisplayMinor = Ft_Esd_LinearRoller_IsDisplayMinor__Default;
	context->IsDisplayAxis = Ft_Esd_LinearRoller_IsDisplayAxis__Default;
	context->MajorWidth = Ft_Esd_LinearRoller_MajorWidth__Default;
	context->MinorWidth = Ft_Esd_LinearRoller_MinorWidth__Default;
	context->TickWidth = Ft_Esd_LinearRoller_TickWidth__Default;
	context->MajorLength = Ft_Esd_LinearRoller_MajorLength__Default;
	context->MinorLength = Ft_Esd_LinearRoller_MinorLength__Default;
	context->TickLength = Ft_Esd_LinearRoller_TickLength__Default;
	context->LabelPadding = Ft_Esd_LinearRoller_LabelPadding__Default;
	Ft_Esd_LinearRoller__TouchScroll__Initializer(context);
}

int Ft_Esd_LinearRoller_TickWidth(Ft_Esd_LinearRoller *context);
void Ft_Esd_LinearRoller_Draw(Ft_Esd_LinearRoller *context);
int Ft_Esd_LinearRoller_UpdateCenterValue(Ft_Esd_LinearRoller *context, bool, float, float, float);
int Ft_Esd_LinearRoller_InitializeCenterValueWithMinMax(Ft_Esd_LinearRoller *context, int, int, int, int);

void Ft_Esd_LinearRoller_Start(Ft_Esd_LinearRoller *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_Start((Ft_Esd_Widget *)context);
	Ft_Esd_TouchScrollLogic_Start(&context->TouchScroll);
}

void Ft_Esd_LinearRoller_Update__Builtin(Ft_Esd_LinearRoller *context)
{
	void *owner = context->Owner;
	Ft_Esd_TouchScrollLogic_Update(&context->TouchScroll);
	Ft_Esd_Widget_Update((Ft_Esd_Widget *)context);
}

void Ft_Esd_LinearRoller_Update(Ft_Esd_LinearRoller *context)
{
	void *owner = context->Owner;
	ft_bool_t isTouched = context->TouchScroll.IsTouched;
	double DeltaX = Ft_Esd_TouchScrollLogic_DeltaX(&context->TouchScroll);
	double DeltaY = Ft_Esd_TouchScrollLogic_DeltaY(&context->TouchScroll);
	int tickWidth = Ft_Esd_LinearRoller_TickWidth(context);
	context->Ft_Esd_LinearRoller_UpdateCenterValue = Ft_Esd_LinearRoller_UpdateCenterValue(context, isTouched, DeltaX, DeltaY, tickWidth);
	int MinInput = context->MinValue(owner);
	int MinVariable_1 = context->MinVariable;
	int MaxInput = context->MaxValue(owner);
	int MaxVariable_1 = context->MaxVariable;
	context->Ft_Esd_LinearRoller_InitializeCenterValueWithMinMax = Ft_Esd_LinearRoller_InitializeCenterValueWithMinMax(context, MinInput, MinVariable_1, MaxInput, MaxVariable_1);
	Ft_Esd_LinearRoller_Update__Builtin(context);
}

void Ft_Esd_LinearRoller_Render(Ft_Esd_LinearRoller *context)
{
	void *owner = context->Owner;
	Ft_Esd_LinearRoller_Draw(context);
	Ft_Esd_Widget_Render((Ft_Esd_Widget *)context); 
}

int Ft_Esd_LinearRoller_CenterValue(Ft_Esd_LinearRoller *context)
{
	void *owner = context->Owner;
	return context->centerValue;
}

ft_argb32_t Ft_Esd_LinearRoller_CenterColor(Ft_Esd_LinearRoller *context)
{
	void *owner = context->Owner;
	return context->centerColor;
}

int Ft_Esd_LinearRoller_TouchScroll_X__Property(void *c)
{
	Ft_Esd_LinearRoller *context = (Ft_Esd_LinearRoller *)c;
	void *owner = context->Owner;
	return context->Widget.GlobalX;
}

int Ft_Esd_LinearRoller_TouchScroll_Y__Property(void *c)
{
	Ft_Esd_LinearRoller *context = (Ft_Esd_LinearRoller *)c;
	void *owner = context->Owner;
	return context->Widget.GlobalY;
}

int Ft_Esd_LinearRoller_TouchScroll_Width__Property(void *c)
{
	Ft_Esd_LinearRoller *context = (Ft_Esd_LinearRoller *)c;
	void *owner = context->Owner;
	return context->Widget.GlobalWidth;
}

int Ft_Esd_LinearRoller_TouchScroll_Height__Property(void *c)
{
	Ft_Esd_LinearRoller *context = (Ft_Esd_LinearRoller *)c;
	void *owner = context->Owner;
	return context->Widget.GlobalHeight;
}

ft_bool_t Ft_Esd_LinearRoller_TouchScroll_EnableXScroll__Property(void *c)
{
	Ft_Esd_LinearRoller *context = (Ft_Esd_LinearRoller *)c;
	void *owner = context->Owner;
	return context->Horizontal(owner);
}

ft_bool_t Ft_Esd_LinearRoller_TouchScroll_EnableYScroll__Property(void *c)
{
	Ft_Esd_LinearRoller *context = (Ft_Esd_LinearRoller *)c;
	void *owner = context->Owner;
	ft_bool_t value = context->Horizontal(owner);
	return !value;
}

int Ft_Esd_LinearRoller_TouchScroll_MinX__Property(void *c)
{
	Ft_Esd_LinearRoller *context = (Ft_Esd_LinearRoller *)c;
	void *owner = context->Owner;
	int left_2 = context->MinValue(owner);
	int right = context->MaxValue(owner);
	ft_float_t left_1 = left_2 - right;
	ft_bool_t if_1 = context->Horizontal(owner);
	int left_3;
	if (if_1)
	{
		left_3 = context->Widget.LocalWidth;
	}
	else
	{
		left_3 = context->Widget.LocalHeight;
	}
	int right_2 = context->Length(owner);
	ft_double_t right_1 = left_3 / right_2;
	ft_double_t left = left_1 * right_1;
	ft_double_t right_3 = 0.5;
	return left - right_3;
}

int Ft_Esd_LinearRoller_TouchScroll_DefaultX__Property(void *c)
{
	Ft_Esd_LinearRoller *context = (Ft_Esd_LinearRoller *)c;
	void *owner = context->Owner;
	int left_6 = context->MinValue(owner);
	int value_1 = context->Value(owner);
	int min = context->MinValue(owner);
	int max = context->MaxValue(owner);
	ft_int32_t right_4 = Ft_Esd_Int32_ClampedValue(value_1, min, max);
	int left_5 = left_6 - right_4;
	ft_bool_t if_2 = context->Horizontal(owner);
	int left_7;
	if (if_2)
	{
		left_7 = context->Widget.LocalWidth;
	}
	else
	{
		left_7 = context->Widget.LocalHeight;
	}
	int right_6 = context->Length(owner);
	ft_double_t right_5 = left_7 / right_6;
	ft_double_t left_4 = left_5 * right_5;
	ft_double_t right_7 = 0.5;
	return left_4 - right_7;
}

int Ft_Esd_LinearRoller_TouchScroll_MinY__Property(void *c)
{
	Ft_Esd_LinearRoller *context = (Ft_Esd_LinearRoller *)c;
	void *owner = context->Owner;
	int left_10 = context->MinValue(owner);
	int right_8 = context->MaxValue(owner);
	ft_float_t left_9 = left_10 - right_8;
	ft_bool_t if_3 = context->Horizontal(owner);
	int left_11;
	if (if_3)
	{
		left_11 = context->Widget.LocalWidth;
	}
	else
	{
		left_11 = context->Widget.LocalHeight;
	}
	int right_10 = context->Length(owner);
	ft_double_t right_9 = left_11 / right_10;
	ft_double_t left_8 = left_9 * right_9;
	ft_double_t right_11 = 0.5;
	return left_8 - right_11;
}

int Ft_Esd_LinearRoller_TouchScroll_DefaultY__Property(void *c)
{
	Ft_Esd_LinearRoller *context = (Ft_Esd_LinearRoller *)c;
	void *owner = context->Owner;
	int left_14 = context->MinValue(owner);
	int value_2 = context->Value(owner);
	int min_1 = context->MinValue(owner);
	int max_1 = context->MaxValue(owner);
	ft_int32_t right_12 = Ft_Esd_Int32_ClampedValue(value_2, min_1, max_1);
	int left_13 = left_14 - right_12;
	ft_bool_t if_4 = context->Horizontal(owner);
	int left_15;
	if (if_4)
	{
		left_15 = context->Widget.LocalWidth;
	}
	else
	{
		left_15 = context->Widget.LocalHeight;
	}
	int right_14 = context->Length(owner);
	ft_double_t right_13 = left_15 / right_14;
	ft_double_t left_12 = left_13 * right_13;
	ft_double_t right_15 = 0.5;
	return left_12 - right_15;
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	Ft_Esd_LinearRoller Instance;
	int Length;
	ft_bool_t Horizontal;
	int MinValue;
	int Value;
	int MaxValue;
	ft_bool_t IsTrimToRange;
	ft_bool_t ShowTrimRange;
	ft_bool_t IsDisplayTick;
	ft_bool_t IsDisplayMinor;
	ft_bool_t IsDisplayAxis;
	int MajorWidth;
	int MinorWidth;
	int TickWidth;
	float MajorLength;
	float MinorLength;
	float TickLength;
	int LabelPadding;
} Ft_Esd_LinearRoller__ESD;

int Ft_Esd_LinearRoller__Get_Length__ESD(void *context) { return ((Ft_Esd_LinearRoller__ESD *)context)->Length; }
void Ft_Esd_LinearRoller__Set_Length__ESD(void *context, int value) { ((Ft_Esd_LinearRoller__ESD *)context)->Length = value; }
ft_bool_t Ft_Esd_LinearRoller__Get_Horizontal__ESD(void *context) { return ((Ft_Esd_LinearRoller__ESD *)context)->Horizontal; }
void Ft_Esd_LinearRoller__Set_Horizontal__ESD(void *context, ft_bool_t value) { ((Ft_Esd_LinearRoller__ESD *)context)->Horizontal = value; }
int Ft_Esd_LinearRoller__Get_MinValue__ESD(void *context) { return ((Ft_Esd_LinearRoller__ESD *)context)->MinValue; }
void Ft_Esd_LinearRoller__Set_MinValue__ESD(void *context, int value) { ((Ft_Esd_LinearRoller__ESD *)context)->MinValue = value; }
int Ft_Esd_LinearRoller__Get_Value__ESD(void *context) { return ((Ft_Esd_LinearRoller__ESD *)context)->Value; }
void Ft_Esd_LinearRoller__Set_Value__ESD(void *context, int value) { ((Ft_Esd_LinearRoller__ESD *)context)->Value = value; }
int Ft_Esd_LinearRoller__Get_MaxValue__ESD(void *context) { return ((Ft_Esd_LinearRoller__ESD *)context)->MaxValue; }
void Ft_Esd_LinearRoller__Set_MaxValue__ESD(void *context, int value) { ((Ft_Esd_LinearRoller__ESD *)context)->MaxValue = value; }
ft_bool_t Ft_Esd_LinearRoller__Get_IsTrimToRange__ESD(void *context) { return ((Ft_Esd_LinearRoller__ESD *)context)->IsTrimToRange; }
void Ft_Esd_LinearRoller__Set_IsTrimToRange__ESD(void *context, ft_bool_t value) { ((Ft_Esd_LinearRoller__ESD *)context)->IsTrimToRange = value; }
ft_bool_t Ft_Esd_LinearRoller__Get_ShowTrimRange__ESD(void *context) { return ((Ft_Esd_LinearRoller__ESD *)context)->ShowTrimRange; }
void Ft_Esd_LinearRoller__Set_ShowTrimRange__ESD(void *context, ft_bool_t value) { ((Ft_Esd_LinearRoller__ESD *)context)->ShowTrimRange = value; }
ft_bool_t Ft_Esd_LinearRoller__Get_IsDisplayTick__ESD(void *context) { return ((Ft_Esd_LinearRoller__ESD *)context)->IsDisplayTick; }
void Ft_Esd_LinearRoller__Set_IsDisplayTick__ESD(void *context, ft_bool_t value) { ((Ft_Esd_LinearRoller__ESD *)context)->IsDisplayTick = value; }
ft_bool_t Ft_Esd_LinearRoller__Get_IsDisplayMinor__ESD(void *context) { return ((Ft_Esd_LinearRoller__ESD *)context)->IsDisplayMinor; }
void Ft_Esd_LinearRoller__Set_IsDisplayMinor__ESD(void *context, ft_bool_t value) { ((Ft_Esd_LinearRoller__ESD *)context)->IsDisplayMinor = value; }
ft_bool_t Ft_Esd_LinearRoller__Get_IsDisplayAxis__ESD(void *context) { return ((Ft_Esd_LinearRoller__ESD *)context)->IsDisplayAxis; }
void Ft_Esd_LinearRoller__Set_IsDisplayAxis__ESD(void *context, ft_bool_t value) { ((Ft_Esd_LinearRoller__ESD *)context)->IsDisplayAxis = value; }
int Ft_Esd_LinearRoller__Get_MajorWidth__ESD(void *context) { return ((Ft_Esd_LinearRoller__ESD *)context)->MajorWidth; }
void Ft_Esd_LinearRoller__Set_MajorWidth__ESD(void *context, int value) { ((Ft_Esd_LinearRoller__ESD *)context)->MajorWidth = value; }
int Ft_Esd_LinearRoller__Get_MinorWidth__ESD(void *context) { return ((Ft_Esd_LinearRoller__ESD *)context)->MinorWidth; }
void Ft_Esd_LinearRoller__Set_MinorWidth__ESD(void *context, int value) { ((Ft_Esd_LinearRoller__ESD *)context)->MinorWidth = value; }
int Ft_Esd_LinearRoller__Get_TickWidth__ESD(void *context) { return ((Ft_Esd_LinearRoller__ESD *)context)->TickWidth; }
void Ft_Esd_LinearRoller__Set_TickWidth__ESD(void *context, int value) { ((Ft_Esd_LinearRoller__ESD *)context)->TickWidth = value; }
float Ft_Esd_LinearRoller__Get_MajorLength__ESD(void *context) { return ((Ft_Esd_LinearRoller__ESD *)context)->MajorLength; }
void Ft_Esd_LinearRoller__Set_MajorLength__ESD(void *context, float value) { ((Ft_Esd_LinearRoller__ESD *)context)->MajorLength = value; }
float Ft_Esd_LinearRoller__Get_MinorLength__ESD(void *context) { return ((Ft_Esd_LinearRoller__ESD *)context)->MinorLength; }
void Ft_Esd_LinearRoller__Set_MinorLength__ESD(void *context, float value) { ((Ft_Esd_LinearRoller__ESD *)context)->MinorLength = value; }
float Ft_Esd_LinearRoller__Get_TickLength__ESD(void *context) { return ((Ft_Esd_LinearRoller__ESD *)context)->TickLength; }
void Ft_Esd_LinearRoller__Set_TickLength__ESD(void *context, float value) { ((Ft_Esd_LinearRoller__ESD *)context)->TickLength = value; }
int Ft_Esd_LinearRoller__Get_LabelPadding__ESD(void *context) { return ((Ft_Esd_LinearRoller__ESD *)context)->LabelPadding; }
void Ft_Esd_LinearRoller__Set_LabelPadding__ESD(void *context, int value) { ((Ft_Esd_LinearRoller__ESD *)context)->LabelPadding = value; }

void *Ft_Esd_LinearRoller__Create__ESD()
{
	Ft_Esd_LinearRoller__ESD *context = (Ft_Esd_LinearRoller__ESD *)malloc(sizeof(Ft_Esd_LinearRoller__ESD));
	if (context)
	{
		Ft_Esd_LinearRoller__Initializer(&context->Instance);
		context->Instance.Owner = context;
		context->Length = 20L;
		context->Instance.Length = Ft_Esd_LinearRoller__Get_Length__ESD;
		context->Horizontal = 1;
		context->Instance.Horizontal = Ft_Esd_LinearRoller__Get_Horizontal__ESD;
		context->MinValue = 0L;
		context->Instance.MinValue = Ft_Esd_LinearRoller__Get_MinValue__ESD;
		context->Value = 0L;
		context->Instance.Value = Ft_Esd_LinearRoller__Get_Value__ESD;
		context->MaxValue = 100L;
		context->Instance.MaxValue = Ft_Esd_LinearRoller__Get_MaxValue__ESD;
		context->IsTrimToRange = 1;
		context->Instance.IsTrimToRange = Ft_Esd_LinearRoller__Get_IsTrimToRange__ESD;
		context->ShowTrimRange = 1;
		context->Instance.ShowTrimRange = Ft_Esd_LinearRoller__Get_ShowTrimRange__ESD;
		context->IsDisplayTick = 1;
		context->Instance.IsDisplayTick = Ft_Esd_LinearRoller__Get_IsDisplayTick__ESD;
		context->IsDisplayMinor = 1;
		context->Instance.IsDisplayMinor = Ft_Esd_LinearRoller__Get_IsDisplayMinor__ESD;
		context->IsDisplayAxis = 1;
		context->Instance.IsDisplayAxis = Ft_Esd_LinearRoller__Get_IsDisplayAxis__ESD;
		context->MajorWidth = 3L;
		context->Instance.MajorWidth = Ft_Esd_LinearRoller__Get_MajorWidth__ESD;
		context->MinorWidth = 2L;
		context->Instance.MinorWidth = Ft_Esd_LinearRoller__Get_MinorWidth__ESD;
		context->TickWidth = 1L;
		context->Instance.TickWidth = Ft_Esd_LinearRoller__Get_TickWidth__ESD;
		context->MajorLength = 0.72f;
		context->Instance.MajorLength = Ft_Esd_LinearRoller__Get_MajorLength__ESD;
		context->MinorLength = 0.6f;
		context->Instance.MinorLength = Ft_Esd_LinearRoller__Get_MinorLength__ESD;
		context->TickLength = 0.56f;
		context->Instance.TickLength = Ft_Esd_LinearRoller__Get_TickLength__ESD;
		context->LabelPadding = 30L;
		context->Instance.LabelPadding = Ft_Esd_LinearRoller__Get_LabelPadding__ESD;
	}
	else
	{
		eve_printf_debug("Out of memory (Ft_Esd_LinearRoller__Create__ESD)");
	}
	return context;
}

void Ft_Esd_LinearRoller__Destroy__ESD(void *context)
{
	free(context);
}

void Ft_Esd_LinearRoller__Set_Major__ESD(void *context, int value) { ((Ft_Esd_LinearRoller__ESD *)context)->Instance.Major = value; }
void Ft_Esd_LinearRoller__Set_Minor__ESD(void *context, int value) { ((Ft_Esd_LinearRoller__ESD *)context)->Instance.Minor = value; }
void Ft_Esd_LinearRoller__Set_ColorMin__ESD(void *context, ft_argb32_t value) { ((Ft_Esd_LinearRoller__ESD *)context)->Instance.ColorMin = value; }
void Ft_Esd_LinearRoller__Set_ColorMax__ESD(void *context, ft_argb32_t value) { ((Ft_Esd_LinearRoller__ESD *)context)->Instance.ColorMax = value; }
void Ft_Esd_LinearRoller__Set_centerValue__ESD(void *context, int value) { ((Ft_Esd_LinearRoller__ESD *)context)->Instance.centerValue = value; }
void Ft_Esd_LinearRoller__Set_centerColor__ESD(void *context, ft_argb32_t value) { ((Ft_Esd_LinearRoller__ESD *)context)->Instance.centerColor = value; }
void Ft_Esd_LinearRoller__Set_MinVariable__ESD(void *context, int value) { ((Ft_Esd_LinearRoller__ESD *)context)->Instance.MinVariable = value; }
void Ft_Esd_LinearRoller__Set_MaxVariable__ESD(void *context, int value) { ((Ft_Esd_LinearRoller__ESD *)context)->Instance.MaxVariable = value; }
void Ft_Esd_LinearRoller__Set_Font__ESD(void *context, uint8_t value) { ((Ft_Esd_LinearRoller__ESD *)context)->Instance.Font = value; }
void Ft_Esd_LinearRoller__Set_valueVariable__ESD(void *context, int value) { ((Ft_Esd_LinearRoller__ESD *)context)->Instance.valueVariable = value; }
void Ft_Esd_LinearRoller__Set_ColorAxis__ESD(void *context, ft_argb32_t value) { ((Ft_Esd_LinearRoller__ESD *)context)->Instance.ColorAxis = value; }

#endif /* ESD_SIMULATION */

/* end of file */
