/*
This file is automatically generated
DO NOT MODIFY BY HAND
Ft_Esd_RangeSliderInterval
Header
*/

#ifndef Ft_Esd_RangeSliderInterval__H
#define Ft_Esd_RangeSliderInterval__H

#include "Esd_Base.h"
#include "Ft_Esd.h"
#include "Ft_Esd_Math.h"
#include "Ft_Esd_Theme.h"
#include "Ft_Esd_TouchTag.h"
#include "Ft_Esd_Widget.h"

#ifndef ESD_LOGIC
#define ESD_LOGIC(name, ...)
#define ESD_ACTOR(name, ...)
#define ESD_WIDGET(name, ...)
#define ESD_PAGE(name, ...)
#define ESD_APPLICATION(name, ...)
#define ESD_INPUT(name, ...)
#define ESD_OUTPUT(name, ...)
#define ESD_SLOT(name, ...)
#define ESD_SIGNAL(name, ...)
#define ESD_VARIABLE(name, ...)
#define ESD_WRITER(name, ...)
#endif

#define Ft_Esd_RangeSliderInterval_CLASSID 0x2CEAEA89
ESD_SYMBOL(Ft_Esd_RangeSliderInterval_CLASSID, Type = esd_classid_t)

/* ESD built-in Range Slider Interval Widget */
ESD_WIDGET(Ft_Esd_RangeSliderInterval, Include = "Ft_Esd_RangeSliderInterval.h", Callback, DisplayName = "ESD RangeSliderInterval", Category = EsdWidgets, Icon = ":/icons/ui-seek-bar.png", X = 0, Y = 0, Width = 160, Height = 20)
typedef struct
{
	union
	{
		void *Owner;
		Ft_Esd_Widget Widget;
	};
	ESD_INPUT(Theme, Type = Ft_Esd_Theme *, Default = Ft_Esd_Theme_GetCurrent)
	Ft_Esd_Theme *(* Theme)(void *context);
	ESD_VARIABLE(inputLeft, Type = int, Default = 20, Private)
	int inputLeft;
	ESD_VARIABLE(inputRight, Type = int, Default = 80, Private)
	int inputRight;
	ESD_INPUT(Min, Type = ft_int32_t)
	ft_int32_t(* Min)(void *context);
	ESD_INPUT(Max, Type = ft_int32_t, Default = 100)
	ft_int32_t(* Max)(void *context);
	ESD_INPUT(Step, Type = ft_int32_t, Default = 5)
	ft_int32_t(* Step)(void *context);
	/* Inclusive range of the RangeSlider value */
	ESD_INPUT(Marker_Lines, Type = ft_bool_t, Default = -1)
	ft_bool_t(* Marker_Lines)(void *context);
	Ft_Esd_TouchTag Touch_Tag;
} Ft_Esd_RangeSliderInterval;

void Ft_Esd_RangeSliderInterval__Initializer(Ft_Esd_RangeSliderInterval *context);

ESD_SLOT(Start)
void Ft_Esd_RangeSliderInterval_Start(Ft_Esd_RangeSliderInterval *context);

ESD_SLOT(End)
void Ft_Esd_RangeSliderInterval_End(Ft_Esd_RangeSliderInterval *context);

ESD_SLOT(Update)
void Ft_Esd_RangeSliderInterval_Update(Ft_Esd_RangeSliderInterval *context);

ESD_OUTPUT(StartValue, Type = int)
int Ft_Esd_RangeSliderInterval_StartValue(Ft_Esd_RangeSliderInterval *context);

ESD_OUTPUT(EndValue, Type = int)
int Ft_Esd_RangeSliderInterval_EndValue(Ft_Esd_RangeSliderInterval *context);

ESD_OUTPUT(Interval, Type = int)
int Ft_Esd_RangeSliderInterval_Interval(Ft_Esd_RangeSliderInterval *context);

ESD_SLOT(Render)
void Ft_Esd_RangeSliderInterval_Render(Ft_Esd_RangeSliderInterval *context);

#endif /* Ft_Esd_RangeSliderInterval__H */

/* end of file */
