/*
This file is automatically generated
DO NOT MODIFY BY HAND
Ft_Esd_RangeSlider
C Source
*/

/*
Comment :
Introduction:
This widget draws a RangeSlider.
Touch input is supported.

*/

#include "Ft_Esd_RangeSlider.h"

#include "Esd_Context.h"
#include "Ft_Esd_CoCmd.h"
#include "Ft_Esd_Dl.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);
Ft_Esd_Theme * Ft_Esd_RangeSlider_Theme__Default(void *context) { return Ft_Esd_Theme_GetCurrent(); }
ft_uint8_t Ft_Esd_RangeSlider_Alpha__Default(void *context) { return 255; }
ft_int16_t Ft_Esd_RangeSlider_Min__Default(void *context) { return 0; }
ft_int16_t Ft_Esd_RangeSlider_Max__Default(void *context) { return 100; }
ft_int16_t Ft_Esd_RangeSlider_Step__Default(void *context) { return 5; }
ft_bool_t Ft_Esd_RangeSlider_Marker_Lines__Default(void *context) { return 1; }
ft_int16_t Ft_Esd_RangeSlider_Value__Default(void *context) { return 5; }


static Ft_Esd_WidgetSlots s_Ft_Esd_RangeSlider__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_RangeSlider_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Ft_Esd_RangeSlider_Update,
	(void(*)(void *))Ft_Esd_RangeSlider_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Ft_Esd_RangeSlider_End,
};

static void Ft_Esd_RangeSlider_TouchTag_Down__Signal(void *context);

void Ft_Esd_RangeSlider__TouchTag__Initializer(Ft_Esd_RangeSlider *context)
{
	Ft_Esd_TouchTag *object = (Ft_Esd_TouchTag *)&context->TouchTag;
	Ft_Esd_TouchTag__Initializer(object);
	object->Owner = (void *)context;
	object->Down = Ft_Esd_RangeSlider_TouchTag_Down__Signal;
}

void Ft_Esd_RangeSlider__Initializer(Ft_Esd_RangeSlider *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Ft_Esd_RangeSlider_CLASSID;
	context->Widget.Slots = &s_Ft_Esd_RangeSlider__Slots;
	context->Widget.LocalX = 50;
	context->Widget.LocalY = 50;
	context->Widget.LocalWidth = 160;
	context->Widget.LocalHeight = 20;
	context->Theme = Ft_Esd_RangeSlider_Theme__Default;
	context->Alpha = Ft_Esd_RangeSlider_Alpha__Default;
	context->Min = Ft_Esd_RangeSlider_Min__Default;
	context->Max = Ft_Esd_RangeSlider_Max__Default;
	context->Step = Ft_Esd_RangeSlider_Step__Default;
	context->Marker_Lines = Ft_Esd_RangeSlider_Marker_Lines__Default;
	context->ValueSlider = 0L;
	context->ValueDisplay = 0L;
	context->Value = Ft_Esd_RangeSlider_Value__Default;
	context->PreviousValue = 0L;
	Ft_Esd_RangeSlider__TouchTag__Initializer(context);
}

static ft_rgb32_t Ft_Esd_RangeSlider_Get_Primary_Color__return(Ft_Esd_RangeSlider *context);
static ft_rgb32_t Ft_Esd_RangeSlider_Get_Default_Color__return(Ft_Esd_RangeSlider *context);
static ft_int16_t Ft_Esd_RangeSlider_Clamp_Int16__return(Ft_Esd_RangeSlider *context);

int Ft_Esd_RangeSlider_ValueX(Ft_Esd_RangeSlider *context, int, int, int, int, int);
void Ft_Esd_RangeSlider_Render_Func(Ft_Esd_RangeSlider *context, int, int, int, int, int, int, int, int, Ft_Esd_Theme *, ft_bool_t);
int Ft_Esd_RangeSlider_StepQuatizedX(Ft_Esd_RangeSlider *context, int, int, int, int);

void Ft_Esd_RangeSlider_Start(Ft_Esd_RangeSlider *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_Start((Ft_Esd_Widget *)context);
	Ft_Esd_TouchTag_Start(&context->TouchTag);
}

void Ft_Esd_RangeSlider_Update__Builtin(Ft_Esd_RangeSlider *context)
{
	void *owner = context->Owner;
	ft_bool_t if_1 = Ft_Esd_TouchTag_Touching(&context->TouchTag);
	int update_variable;
	if (if_1)
	{
		ft_int16_t GlobalWidgetX = context->Widget.GlobalX;
		ft_int16_t WidgetWidth = context->Widget.GlobalWidth;
		ft_int16_t TouchX = Ft_Esd_TouchTag_TouchX(&context->TouchTag);
		ft_int16_t Min_1 = context->Min(owner);
		ft_int16_t Max_1 = context->Max(owner);
		update_variable = Ft_Esd_RangeSlider_ValueX(context, GlobalWidgetX, WidgetWidth, TouchX, Min_1, Max_1);
	}
	else
	{
		update_variable = context->ValueSlider;
	}
	context->ValueSlider = update_variable;
	ft_int16_t Min_2 = context->Min(owner);
	ft_int16_t Max_2 = context->Max(owner);
	ft_int16_t Step_1 = context->Step(owner);
	int Value_1 = context->ValueSlider;
	int update_variable_1 = Ft_Esd_RangeSlider_StepQuatizedX(context, Min_2, Max_2, Step_1, Value_1);
	context->ValueDisplay = update_variable_1;
	Ft_Esd_Widget_Update((Ft_Esd_Widget *)context);
}

void Ft_Esd_RangeSlider_End(Ft_Esd_RangeSlider *context)
{
	void *owner = context->Owner;
	Ft_Esd_TouchTag_End(&context->TouchTag);
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
}

void Ft_Esd_RangeSlider_Render(Ft_Esd_RangeSlider *context)
{
	void *owner = context->Owner;
	ft_uint8_t alpha = context->Alpha(owner);
	Ft_Esd_Dl_COLOR_A(alpha);
	ft_bool_t if_2 = Ft_Esd_TouchTag_Touching(&context->TouchTag);
	ft_rgb32_t c_1;
	if (if_2)
	{
		c_1 = Ft_Esd_RangeSlider_Get_Primary_Color__return(context);
	}
	else
	{
		c_1 = Ft_Esd_RangeSlider_Get_Default_Color__return(context);
	}
	Ft_Esd_Dl_COLOR_RGB(c_1);
	EVE_HalContext * phost = Ft_Esd_GetHost();
	ft_bool_t if_3 = Ft_Esd_TouchTag_Touching(&context->TouchTag);
	ft_rgb32_t c_2;
	if (if_3)
	{
		c_2 = Ft_Esd_RangeSlider_Get_Default_Color__return(context);
	}
	else
	{
		Ft_Esd_Theme * theme = context->Theme(owner);
		c_2 = Ft_Esd_Theme_GetBackColor(theme);
	}
	Ft_Gpu_CoCmd_BgColor(phost, c_2);
	EVE_HalContext * phost_1 = Ft_Esd_GetHost();
	ft_rgb32_t c_3 = Ft_Esd_RangeSlider_Get_Primary_Color__return(context);
	Ft_Gpu_CoCmd_FgColor(phost_1, c_3);
	ft_uint8_t s = Ft_Esd_TouchTag_Tag(&context->TouchTag);
	Ft_Esd_Dl_TAG(s);
	ft_int16_t x = context->Widget.GlobalX;
	ft_int16_t y = context->Widget.GlobalY;
	ft_int16_t width = context->Widget.GlobalWidth;
	ft_int16_t height = context->Widget.GlobalHeight;
	ft_int16_t min = context->Min(owner);
	ft_int16_t max = context->Max(owner);
	ft_int16_t step = context->Step(owner);
	int value = context->ValueSlider;
	Ft_Esd_Theme * theme_1 = context->Theme(owner);
	ft_bool_t markerlines = context->Marker_Lines(owner);
	Ft_Esd_RangeSlider_Render_Func(context, x, y, width, height, min, max, step, value, theme_1, markerlines);
	ft_uint8_t s_1 = 255;
	Ft_Esd_Dl_TAG(s_1);
	Ft_Esd_Widget_Render((Ft_Esd_Widget *)context); 
}

ft_rgb32_t Ft_Esd_RangeSlider_Get_Primary_Color__return(Ft_Esd_RangeSlider *context)
{
	void *owner = context->Owner;
	Ft_Esd_Theme * theme_2 = context->Theme(owner);
	return Ft_Esd_Theme_GetPrimaryColor(theme_2);
}

void Ft_Esd_RangeSlider_Update(Ft_Esd_RangeSlider *context)
{
	void *owner = context->Owner;
	Ft_Esd_TouchTag_Update(&context->TouchTag);
	ft_int16_t left = Ft_Esd_RangeSlider_Clamp_Int16__return(context);
	int right = context->PreviousValue;
	int if_4 = left != right;
	if (if_4)
	{
		ft_int16_t set_variable = Ft_Esd_RangeSlider_Clamp_Int16__return(context);
		context->ValueSlider = set_variable;
		context->PreviousValue = set_variable;
	}
	else
	{
	}
	Ft_Esd_RangeSlider_Update__Builtin(context);
}

ft_rgb32_t Ft_Esd_RangeSlider_Get_Default_Color__return(Ft_Esd_RangeSlider *context)
{
	void *owner = context->Owner;
	Ft_Esd_Theme * theme_3 = context->Theme(owner);
	return Ft_Esd_Theme_GetCurrentColor(theme_3);
}

int Ft_Esd_RangeSlider_Output(Ft_Esd_RangeSlider *context)
{
	void *owner = context->Owner;
	return context->ValueDisplay;
}

ft_int16_t Ft_Esd_RangeSlider_Clamp_Int16__return(Ft_Esd_RangeSlider *context)
{
	void *owner = context->Owner;
	ft_int16_t value_1 = context->Value(owner);
	ft_int16_t min_1 = context->Min(owner);
	ft_int16_t max_1 = context->Max(owner);
	return Ft_Esd_Int16_ClampedValue(value_1, min_1, max_1);
}

void Ft_Esd_RangeSlider_TouchTag_Down__Signal(void *c)
{
	Ft_Esd_RangeSlider *context = (Ft_Esd_RangeSlider *)c;
	void *owner = context->Owner;
	// Variable writer 'Set_Variable_2' does not write to any variables
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	Ft_Esd_RangeSlider Instance;
	Ft_Esd_Theme * Theme;
	ft_uint8_t Alpha;
	ft_int16_t Min;
	ft_int16_t Max;
	ft_int16_t Step;
	ft_bool_t Marker_Lines;
	ft_int16_t Value;
} Ft_Esd_RangeSlider__ESD;

Ft_Esd_Theme * Ft_Esd_RangeSlider__Get_Theme__ESD(void *context) { return ((Ft_Esd_RangeSlider__ESD *)context)->Theme; }
void Ft_Esd_RangeSlider__Set_Theme__ESD(void *context, Ft_Esd_Theme * value) { ((Ft_Esd_RangeSlider__ESD *)context)->Theme = value; }
ft_uint8_t Ft_Esd_RangeSlider__Get_Alpha__ESD(void *context) { return ((Ft_Esd_RangeSlider__ESD *)context)->Alpha; }
void Ft_Esd_RangeSlider__Set_Alpha__ESD(void *context, ft_uint8_t value) { ((Ft_Esd_RangeSlider__ESD *)context)->Alpha = value; }
ft_int16_t Ft_Esd_RangeSlider__Get_Min__ESD(void *context) { return ((Ft_Esd_RangeSlider__ESD *)context)->Min; }
void Ft_Esd_RangeSlider__Set_Min__ESD(void *context, ft_int16_t value) { ((Ft_Esd_RangeSlider__ESD *)context)->Min = value; }
ft_int16_t Ft_Esd_RangeSlider__Get_Max__ESD(void *context) { return ((Ft_Esd_RangeSlider__ESD *)context)->Max; }
void Ft_Esd_RangeSlider__Set_Max__ESD(void *context, ft_int16_t value) { ((Ft_Esd_RangeSlider__ESD *)context)->Max = value; }
ft_int16_t Ft_Esd_RangeSlider__Get_Step__ESD(void *context) { return ((Ft_Esd_RangeSlider__ESD *)context)->Step; }
void Ft_Esd_RangeSlider__Set_Step__ESD(void *context, ft_int16_t value) { ((Ft_Esd_RangeSlider__ESD *)context)->Step = value; }
ft_bool_t Ft_Esd_RangeSlider__Get_Marker_Lines__ESD(void *context) { return ((Ft_Esd_RangeSlider__ESD *)context)->Marker_Lines; }
void Ft_Esd_RangeSlider__Set_Marker_Lines__ESD(void *context, ft_bool_t value) { ((Ft_Esd_RangeSlider__ESD *)context)->Marker_Lines = value; }
ft_int16_t Ft_Esd_RangeSlider__Get_Value__ESD(void *context) { return ((Ft_Esd_RangeSlider__ESD *)context)->Value; }
void Ft_Esd_RangeSlider__Set_Value__ESD(void *context, ft_int16_t value) { ((Ft_Esd_RangeSlider__ESD *)context)->Value = value; }

void *Ft_Esd_RangeSlider__Create__ESD()
{
	Ft_Esd_RangeSlider__ESD *context = (Ft_Esd_RangeSlider__ESD *)malloc(sizeof(Ft_Esd_RangeSlider__ESD));
	if (context)
	{
		Ft_Esd_RangeSlider__Initializer(&context->Instance);
		context->Instance.Owner = context;
		context->Theme = Ft_Esd_Theme_GetCurrent();
		context->Instance.Theme = Ft_Esd_RangeSlider__Get_Theme__ESD;
		context->Alpha = 255;
		context->Instance.Alpha = Ft_Esd_RangeSlider__Get_Alpha__ESD;
		context->Min = 0;
		context->Instance.Min = Ft_Esd_RangeSlider__Get_Min__ESD;
		context->Max = 100;
		context->Instance.Max = Ft_Esd_RangeSlider__Get_Max__ESD;
		context->Step = 5;
		context->Instance.Step = Ft_Esd_RangeSlider__Get_Step__ESD;
		context->Marker_Lines = 1;
		context->Instance.Marker_Lines = Ft_Esd_RangeSlider__Get_Marker_Lines__ESD;
		context->Value = 5;
		context->Instance.Value = Ft_Esd_RangeSlider__Get_Value__ESD;
	}
	else
	{
		eve_printf_debug("Out of memory (Ft_Esd_RangeSlider__Create__ESD)");
	}
	return context;
}

void Ft_Esd_RangeSlider__Destroy__ESD(void *context)
{
	free(context);
}

void Ft_Esd_RangeSlider__Set_ValueSlider__ESD(void *context, int value) { ((Ft_Esd_RangeSlider__ESD *)context)->Instance.ValueSlider = value; }
void Ft_Esd_RangeSlider__Set_ValueDisplay__ESD(void *context, int value) { ((Ft_Esd_RangeSlider__ESD *)context)->Instance.ValueDisplay = value; }
void Ft_Esd_RangeSlider__Set_PreviousValue__ESD(void *context, int value) { ((Ft_Esd_RangeSlider__ESD *)context)->Instance.PreviousValue = value; }

#endif /* ESD_SIMULATION */

/* end of file */
